image: Visual Studio 2015

build_script:
  - mkdir C:\kfw
  - set KRB_INSTALL_DIR=C:\kfw
  - cd %APPVEYOR_BUILD_FOLDER%\src
  - set PATH=%PATH%;%wix%bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - set CPU=i386
  - set
  - nmake -f Makefile.in prep-windows
  - nmake
  - nmake install
  - cd windows\installer\wix
  - nmake
  - rename kfw.msi kfw32.msi
  - cd ..\..\..
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - set CPU=AMD64
  - set
  - nmake clean
  - nmake
  - nmake install
  - cd windows\installer\wix
  - nmake clean
  - nmake
  - rename kfw.msi kfw64.msi
