name: Build

on:
    push: {paths: [src/**, .github/workflows/build.yml]}
    pull_request: {paths: [src/**, .github/workflows/build.yml]}

jobs:

    windows:
        runs-on: windows-2019
        env:
            KRB_INSTALL_DIR: C:\kfw
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1
            - name: Setup
              shell: cmd
              run: |
                mkdir %KRB_INSTALL_DIR%
            - name: Build 32-bit
              shell: cmd
              run: |
                cd src
                call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
                set
                set PATH=%PATH%;%wix%bin
                nmake -f Makefile.in prep-windows
                nmake
                nmake install
                cd windows\installer\wix
                nmake
                rename kfw.msi kfw32.msi
            - name: Build 64-bit
              shell: cmd
              run: |
                cd src
                call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
                set
                set PATH=%PATH%;%wix%bin;"%WindowsSdkVerBinPath%"\x86
                nmake clean
                nmake
                nmake install
                cd windows\installer\wix
                nmake clean
                nmake
                rename kfw.msi kfw64.msi
