name: Build

on: [push, pull_request]

jobs:

    unix:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                name: [macos-clang]
                include:
                    - name: macos-clang
                      os: macos-latest
                      compiler: clang
                      configureopts: CPPFLAGS=-I/usr/local/opt/openssl/include LDFLAGS=-L/usr/local/opt/openssl/lib
                      env:
                        PATH: /usr/local/opt/bison/bin:/usr/local/opt/tcl-tk/bin:$PATH
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1
            - name: Linux setup
              if: startsWith(matrix.os, 'ubuntu')
              run: |
                sudo apt-get update -qq
                sudo apt-get install -y bison gettext keyutils ldap-utils libcmocka-dev libldap2-dev libkeyutils-dev libresolv-wrapper libsasl2-dev libssl-dev python3-kdcproxy python3-pip slapd tcsh
                pip3 install pyrad
            - name: macOS setup
              if: matrix.os == 'macos-latest'
              run: |
                brew update
                brew install bison openldap openssl deja-gnu automake tcl-tk
            - name: Build
              env:
                CC: ${{ matrix.compiler }}
                MAKEVARS: ${{ matrix.makevars }}
                CONFIGURE_OPTS:  ${{ matrix.configureopts }}
              run: |
                cd src
                autoreconf
                ./configure --enable-maintainer-mode --with-ldap $CONFIGURE_OPTS --prefix=$HOME/inst
                make $MAKEVARS && make install || true
            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3
